# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import neuroservice_pb2 as neuroservice__pb2


class NeuroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePicture = channel.unary_unary(
                '/neuroproto.NeuroService/GeneratePicture',
                request_serializer=neuroservice__pb2.GeneratePictureRequest.SerializeToString,
                response_deserializer=neuroservice__pb2.GeneratePictureResponse.FromString,
                )


class NeuroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeuroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePicture,
                    request_deserializer=neuroservice__pb2.GeneratePictureRequest.FromString,
                    response_serializer=neuroservice__pb2.GeneratePictureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neuroproto.NeuroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NeuroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neuroproto.NeuroService/GeneratePicture',
            neuroservice__pb2.GeneratePictureRequest.SerializeToString,
            neuroservice__pb2.GeneratePictureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
