# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neuroservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12neuroservice.proto\x12\nneuroproto\"C\n\x16GeneratePictureRequest\x12\x15\n\rOriginalImage\x18\x01 \x01(\x0c\x12\x12\n\nStyleImage\x18\x02 \x01(\x0c\".\n\x17GeneratePictureResponse\x12\x13\n\x0bResultImage\x18\x01 \x01(\x0c\x32l\n\x0cNeuroService\x12\\\n\x0fGeneratePicture\x12\".neuroproto.GeneratePictureRequest\x1a#.neuroproto.GeneratePictureResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neuroservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERATEPICTUREREQUEST']._serialized_start=34
  _globals['_GENERATEPICTUREREQUEST']._serialized_end=101
  _globals['_GENERATEPICTURERESPONSE']._serialized_start=103
  _globals['_GENERATEPICTURERESPONSE']._serialized_end=149
  _globals['_NEUROSERVICE']._serialized_start=151
  _globals['_NEUROSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
